# Generated by Django 6.0 on 2025-12-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_admission',
            field=models.IntegerField(default=2025),
        ),
    ]
